const std = @import("std");

/// Generate the common zdl.h header file with shared types for all schemas.
/// This includes error codes, comparison operators, field types, and field info struct.
pub fn generateCommonHeader(writer: anytype) !void {
    try writer.writeAll(
        \\// zdl.h - Common types for all zdl schemas
        \\// Auto-generated by zdl - do not edit manually
        \\
        \\#ifndef ZDL_H
        \\#define ZDL_H
        \\
        \\#include <stdint.h>
        \\#include <stddef.h>
        \\#include <stdbool.h>
        \\
        \\#ifdef __cplusplus
        \\extern "C" {
        \\#endif
        \\
        \\// Serialization target
        \\typedef enum {
        \\    ZDL_TARGET_CPU = 0,
        \\    ZDL_TARGET_DISK = 1,
        \\    ZDL_TARGET_NETWORK = 2
        \\} zdl_target_t;
        \\
        \\// Comparison operators for query filters
        \\typedef enum {
        \\    ZDL_EQ = 0,   // Equal
        \\    ZDL_NE = 1,   // Not equal
        \\    ZDL_LT = 2,   // Less than
        \\    ZDL_LE = 3,   // Less than or equal
        \\    ZDL_GT = 4,   // Greater than
        \\    ZDL_GE = 5    // Greater than or equal
        \\} zdl_cmp_t;
        \\
        \\// Error codes
        \\typedef enum {
        \\    ZDL_OK = 0,
        \\    ZDL_ERR_NULL = 1,           // Null parameter provided
        \\    ZDL_ERR_INVALID_FIELD = 2,  // Invalid field name
        \\    ZDL_ERR_TYPE_MISMATCH = 3,  // Type mismatch in filter value
        \\    ZDL_ERR_CORRUPT = 4,        // Buffer is corrupt or invalid
        \\    ZDL_ERR_OOM = 5,            // Out of memory
        \\    ZDL_ERR_LIMIT_EXCEEDED = 6, // Result limit exceeded
        \\    ZDL_ERR_LIMIT_REQUIRED = 7, // Limit required for collect operation
        \\    ZDL_ERR_TOO_MANY_FILTERS = 8, // Too many filters applied
        \\    ZDL_ERR_ITER_NOT_STARTED = 9, // Iterator not started
        \\    ZDL_ERR_UNSUPPORTED_TYPE = 10, // Unsupported field type for filtering
        \\    ZDL_ERR_CAPACITY_FULL = 11,    // Container capacity full (call reserve)
        \\    ZDL_ERR_STALE_VIEW = 12,       // View invalidated by compact/reserve fence
        \\    ZDL_ERR_SLOT_OUT_OF_RANGE = 13, // Slot index out of range
        \\    ZDL_ERR_SLOT_DELETED = 14,     // Record at slot is deleted
        \\    ZDL_ERR_CHECKSUM = 15,         // Record or container checksum mismatch
        \\    ZDL_ERR_VERSION = 16,          // Container schema version mismatch
        \\    ZDL_ERR_BUFFER_TOO_SMALL = 17, // Destination buffer too small
        \\    ZDL_ERR_DATA_TOO_LARGE = 18    // Data exceeds maximum container size
        \\} zdl_error_t;
        \\
        \\// Field type codes for introspection
        \\typedef enum {
        \\    ZDL_TYPE_BOOL = 0,
        \\    ZDL_TYPE_I8 = 1,
        \\    ZDL_TYPE_I16 = 2,
        \\    ZDL_TYPE_I32 = 3,
        \\    ZDL_TYPE_I64 = 4,
        \\    ZDL_TYPE_U8 = 5,
        \\    ZDL_TYPE_U16 = 6,
        \\    ZDL_TYPE_U32 = 7,
        \\    ZDL_TYPE_U64 = 8,
        \\    ZDL_TYPE_F32 = 9,
        \\    ZDL_TYPE_F64 = 10,
        \\    ZDL_TYPE_BYTES = 11,
        \\    ZDL_TYPE_STRUCT = 12
        \\} zdl_field_type_t;
        \\
        \\// Field info for runtime introspection
        \\typedef struct {
        \\    const char* name;           // Field name (null-terminated)
        \\    zdl_field_type_t type;      // Field type
        \\    size_t offset;              // Byte offset within struct
        \\    size_t size;                // Size in bytes
        \\    size_t array_len;           // Array length (0 if not an array)
        \\} zdl_field_info_t;
        \\
        \\// Global error handling
        \\// Returns the last error code for the current thread
        \\zdl_error_t zdl_last_error(void);
        \\
        \\// Returns a human-readable error message for the given error code
        \\const char* zdl_error_message(zdl_error_t err);
        \\
        \\#ifdef __cplusplus
        \\}
        \\#endif
        \\
        \\#endif // ZDL_H
        \\
    );
}
