const std = @import("std");
const zdl = @import("zdl");
const schemas = zdl.interop.schemas;
const c_header = zdl.codegen.c_header;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len < 2) {
        std.debug.print("usage: gen_python <output_dir>\n", .{});
        return error.InvalidArgs;
    }

    const output_dir_path = args[1];
    var dir = try std.fs.cwd().makeOpenPath(output_dir_path, .{});
    defer dir.close();

    // Generate the main zdl.py module
    {
        var file = try dir.createFile("zdl.py", .{ .truncate = true });
        defer file.close();

        var list = std.ArrayListUnmanaged(u8){};
        defer list.deinit(allocator);

        try generatePythonModule(list.writer(allocator));
        try file.writeAll(list.items);

        std.debug.print("generated zdl.py\n", .{});
    }
}

fn generatePythonModule(writer: anytype) !void {
    // Write module header
    try writer.writeAll(
        \\"""
        \\zdl - Zero-copy Data Language Python bindings
        \\
        \\Auto-generated by zdl - do not edit manually.
        \\
        \\Usage:
        \\    from zdl import FfiUser, Target
        \\
        \\    # Create and serialize
        \\    user = FfiUser(id=42, score=3.14, name=b"hello")
        \\    data = user.serialize(Target.CPU)
        \\
        \\    # Deserialize
        \\    user2 = FfiUser.deserialize(data)
        \\
        \\    # Query
        \\    query = FfiUserQuery(data)
        \\    results = query.filter("id", ">=", 10).limit(100).collect()
        \\"""
        \\
        \\from __future__ import annotations
        \\import ctypes
        \\from ctypes import (
        \\    c_int, c_uint8, c_int8, c_uint16, c_int16, c_uint32, c_int32,
        \\    c_uint64, c_int64, c_float, c_double, c_bool, c_size_t, c_char_p,
        \\    c_void_p, POINTER, Structure, byref, cast
        \\)
        \\from dataclasses import dataclass, field
        \\from enum import IntEnum
        \\from pathlib import Path
        \\from typing import Iterator, List, Optional, Union, Any
        \\import os
        \\import sys
        \\
        \\# Load the shared library
        \\def _find_library() -> str:
        \\    """Find the zdl shared library."""
        \\    # Check common locations
        \\    search_paths = [
        \\        Path(__file__).parent / "libzdl.so",
        \\        Path(__file__).parent / "libzdl.dylib",
        \\        Path(__file__).parent / "zdl.dll",
        \\        Path(__file__).parent.parent / "lib" / "libzdl.so",
        \\        Path(__file__).parent.parent / "zig-out" / "lib" / "libzdl.so",
        \\    ]
        \\
        \\    # Also check LD_LIBRARY_PATH
        \\    ld_path = os.environ.get("LD_LIBRARY_PATH", "")
        \\    for p in ld_path.split(":"):
        \\        if p:
        \\            search_paths.append(Path(p) / "libzdl.so")
        \\
        \\    for path in search_paths:
        \\        if path.exists():
        \\            return str(path)
        \\
        \\    # Fall back to system loader
        \\    return "libzdl.so"
        \\
        \\_lib = ctypes.CDLL(_find_library())
        \\
        \\
        \\class Target(IntEnum):
        \\    """Serialization target."""
        \\    CPU = 0
        \\    DISK = 1
        \\    NETWORK = 2
        \\
        \\
        \\class Comparison(IntEnum):
        \\    """Comparison operators for query filters."""
        \\    EQ = 0  # Equal
        \\    NE = 1  # Not equal
        \\    LT = 2  # Less than
        \\    LE = 3  # Less than or equal
        \\    GT = 4  # Greater than
        \\    GE = 5  # Greater than or equal
        \\
        \\
        \\class ZdlError(IntEnum):
        \\    """Error codes from zdl operations."""
        \\    OK = 0
        \\    NULL_PARAM = 1
        \\    INVALID_FIELD = 2
        \\    TYPE_MISMATCH = 3
        \\    BUFFER_CORRUPT = 4
        \\    OUT_OF_MEMORY = 5
        \\    LIMIT_EXCEEDED = 6
        \\    LIMIT_REQUIRED = 7
        \\    TOO_MANY_FILTERS = 8
        \\    ITERATOR_NOT_STARTED = 9
        \\    UNSUPPORTED_TYPE = 10
        \\
        \\
        \\class FieldType(IntEnum):
        \\    """Field type codes for introspection."""
        \\    BOOL = 0
        \\    I8 = 1
        \\    I16 = 2
        \\    I32 = 3
        \\    I64 = 4
        \\    U8 = 5
        \\    U16 = 6
        \\    U32 = 7
        \\    U64 = 8
        \\    F32 = 9
        \\    F64 = 10
        \\    BYTES = 11
        \\    STRUCT = 12
        \\
        \\
        \\class ZdlException(Exception):
        \\    """Exception raised by zdl operations."""
        \\    def __init__(self, code: ZdlError, message: str = ""):
        \\        self.code = code
        \\        self.message = message or _get_error_message(code)
        \\        super().__init__(f"{self.code.name}: {self.message}")
        \\
        \\
        \\# Global error functions
        \\_lib.zdl_last_error.restype = c_int
        \\_lib.zdl_last_error.argtypes = []
        \\
        \\_lib.zdl_error_message.restype = c_char_p
        \\_lib.zdl_error_message.argtypes = [c_int]
        \\
        \\
        \\def _get_last_error() -> ZdlError:
        \\    """Get the last error code."""
        \\    return ZdlError(_lib.zdl_last_error())
        \\
        \\
        \\def _get_error_message(code: ZdlError) -> str:
        \\    """Get error message for a code."""
        \\    result = _lib.zdl_error_message(code)
        \\    return result.decode("utf-8") if result else "Unknown error"
        \\
        \\
        \\def _check_error(code: int) -> None:
        \\    """Check error code and raise exception if not OK."""
        \\    if code != ZdlError.OK:
        \\        raise ZdlException(ZdlError(code))
        \\
        \\
        \\def _cmp_from_str(op: str) -> Comparison:
        \\    """Convert string operator to Comparison enum."""
        \\    mapping = {
        \\        "==": Comparison.EQ, "=": Comparison.EQ, "eq": Comparison.EQ,
        \\        "!=": Comparison.NE, "<>": Comparison.NE, "ne": Comparison.NE,
        \\        "<": Comparison.LT, "lt": Comparison.LT,
        \\        "<=": Comparison.LE, "le": Comparison.LE,
        \\        ">": Comparison.GT, "gt": Comparison.GT,
        \\        ">=": Comparison.GE, "ge": Comparison.GE,
        \\    }
        \\    if op not in mapping:
        \\        raise ValueError(f"Unknown comparison operator: {op}")
        \\    return mapping[op]
        \\
        \\
    );

    // Generate schema-specific classes
    inline for (schemas.registry) |entry| {
        try generateSchemaClass(entry.Type, entry.c_prefix, writer);
    }
}

fn generateSchemaClass(comptime T: type, comptime prefix: []const u8, writer: anytype) !void {
    const type_name = c_header.simplifyTypeName(@typeName(T));
    const fields = std.meta.fields(T);

    // Count non-comptime fields
    comptime var field_count: usize = 0;
    inline for (fields) |fld| {
        if (!fld.is_comptime) field_count += 1;
    }

    // Generate ctypes Structure
    try writer.print(
        \\
        \\# ========== {s} ==========
        \\
        \\class _{s}Struct(Structure):
        \\    """C structure layout for {s}."""
        \\    _fields_ = [
        \\
    , .{ type_name, type_name, type_name });

    inline for (fields) |fld| {
        if (fld.is_comptime) continue;
        const ctype = comptime ctypeForZigType(fld.type);
        try writer.print("        (\"{s}\", {s}),\n", .{ fld.name, ctype });
    }

    try writer.writeAll("    ]\n\n");

    // Set up library function signatures - broken into smaller pieces
    try writer.print("\n# Function signatures for {s}\n", .{type_name});

    // Serialize/deserialize
    try writer.print("_lib.{s}_serialize.restype = POINTER(c_uint8)\n", .{prefix});
    try writer.print("_lib.{s}_serialize.argtypes = [POINTER(_{s}Struct), c_int, POINTER(c_size_t)]\n\n", .{ prefix, type_name });

    try writer.print("_lib.{s}_deserialize.restype = POINTER(_{s}Struct)\n", .{ prefix, type_name });
    try writer.print("_lib.{s}_deserialize.argtypes = [POINTER(c_uint8), c_size_t]\n\n", .{prefix});

    try writer.print("_lib.{s}_free.restype = None\n", .{prefix});
    try writer.print("_lib.{s}_free.argtypes = [c_void_p]\n\n", .{prefix});

    // Array functions
    try writer.print("_lib.{s}_serialize_array.restype = POINTER(c_uint8)\n", .{prefix});
    try writer.print("_lib.{s}_serialize_array.argtypes = [POINTER(_{s}Struct), c_size_t, c_int, POINTER(c_size_t)]\n\n", .{ prefix, type_name });

    try writer.print("_lib.{s}_array_count.restype = c_uint64\n", .{prefix});
    try writer.print("_lib.{s}_array_count.argtypes = [POINTER(c_uint8), c_size_t]\n\n", .{prefix});

    // Query functions
    try writer.print("_lib.{s}_query_new.restype = c_void_p\n", .{prefix});
    try writer.print("_lib.{s}_query_new.argtypes = [POINTER(c_uint8), c_size_t]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_free.restype = None\n", .{prefix});
    try writer.print("_lib.{s}_query_free.argtypes = [c_void_p]\n\n", .{prefix});

    // Filter functions
    try writer.print("_lib.{s}_query_filter_u64.restype = c_int\n", .{prefix});
    try writer.print("_lib.{s}_query_filter_u64.argtypes = [c_void_p, c_char_p, c_int, c_uint64]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_filter_i64.restype = c_int\n", .{prefix});
    try writer.print("_lib.{s}_query_filter_i64.argtypes = [c_void_p, c_char_p, c_int, c_int64]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_filter_f32.restype = c_int\n", .{prefix});
    try writer.print("_lib.{s}_query_filter_f32.argtypes = [c_void_p, c_char_p, c_int, c_float]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_filter_f64.restype = c_int\n", .{prefix});
    try writer.print("_lib.{s}_query_filter_f64.argtypes = [c_void_p, c_char_p, c_int, c_double]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_filter_bool.restype = c_int\n", .{prefix});
    try writer.print("_lib.{s}_query_filter_bool.argtypes = [c_void_p, c_char_p, c_int, c_bool]\n\n", .{prefix});

    // Limit/offset/collect/count
    try writer.print("_lib.{s}_query_limit.restype = c_int\n", .{prefix});
    try writer.print("_lib.{s}_query_limit.argtypes = [c_void_p, c_size_t]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_offset.restype = c_int\n", .{prefix});
    try writer.print("_lib.{s}_query_offset.argtypes = [c_void_p, c_size_t]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_collect.restype = POINTER(_{s}Struct)\n", .{ prefix, type_name });
    try writer.print("_lib.{s}_query_collect.argtypes = [c_void_p, POINTER(c_size_t)]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_count.restype = c_uint64\n", .{prefix});
    try writer.print("_lib.{s}_query_count.argtypes = [c_void_p]\n\n", .{prefix});

    // Iterator functions
    try writer.print("_lib.{s}_query_iter_start.restype = c_int\n", .{prefix});
    try writer.print("_lib.{s}_query_iter_start.argtypes = [c_void_p]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_iter_next.restype = POINTER(_{s}Struct)\n", .{ prefix, type_name });
    try writer.print("_lib.{s}_query_iter_next.argtypes = [c_void_p]\n\n", .{prefix});

    try writer.print("_lib.{s}_query_iter_reset.restype = None\n", .{prefix});
    try writer.print("_lib.{s}_query_iter_reset.argtypes = [c_void_p]\n\n", .{prefix});

    // Introspection functions
    try writer.print("_lib.{s}_field_count.restype = c_size_t\n", .{prefix});
    try writer.print("_lib.{s}_field_count.argtypes = []\n\n", .{prefix});

    try writer.print("_lib.{s}_struct_size.restype = c_size_t\n", .{prefix});
    try writer.print("_lib.{s}_struct_size.argtypes = []\n\n", .{prefix});

    // Generate the dataclass
    try writer.print(
        \\@dataclass
        \\class {s}:
        \\    """
        \\    {s} schema - zdl serializable data structure.
        \\
        \\    Fields:
        \\
    , .{ type_name, type_name });

    inline for (fields) |fld| {
        if (fld.is_comptime) continue;
        const pytype = comptime pytypeForZigType(fld.type);
        try writer.print("        {s}: {s}\n", .{ fld.name, pytype });
    }

    try writer.writeAll("    \"\"\"\n");

    // Field declarations
    inline for (fields) |fld| {
        if (fld.is_comptime) continue;
        const pytype = comptime pytypeForZigType(fld.type);
        const default_val = comptime defaultForZigType(fld.type);
        try writer.print("    {s}: {s} = {s}\n", .{ fld.name, pytype, default_val });
    }

    // _to_struct method
    try writer.print(
        \\
        \\    def _to_struct(self) -> _{s}Struct:
        \\        """Convert to C structure."""
        \\        s = _{s}Struct()
        \\
    , .{ type_name, type_name });

    inline for (fields) |fld| {
        if (fld.is_comptime) continue;
        if (comptime isArrayType(fld.type)) {
            const arr_info = @typeInfo(fld.type).array;
            try writer.print("        val_{s} = self.{s}\n", .{ fld.name, fld.name });
            try writer.print("        if isinstance(val_{s}, str):\n", .{fld.name});
            try writer.print("            val_{s} = val_{s}.encode(\"utf-8\")\n", .{ fld.name, fld.name });
            try writer.print("        for i, b in enumerate(val_{s}[:{d}]):\n", .{ fld.name, arr_info.len });
            try writer.print("            s.{s}[i] = b\n", .{fld.name});
        } else {
            try writer.print("        s.{s} = self.{s}\n", .{ fld.name, fld.name });
        }
    }

    try writer.writeAll("        return s\n");

    // _from_struct method
    try writer.print(
        \\
        \\    @classmethod
        \\    def _from_struct(cls, s: _{s}Struct) -> "{s}":
        \\        """Create from C structure."""
        \\        return cls(
        \\
    , .{ type_name, type_name });

    var first = true;
    inline for (fields) |fld| {
        if (fld.is_comptime) continue;
        if (!first) {
            try writer.writeAll(",\n");
        }
        first = false;
        if (comptime isArrayType(fld.type)) {
            try writer.print("            {s}=bytes(s.{s})", .{ fld.name, fld.name });
        } else {
            try writer.print("            {s}=s.{s}", .{ fld.name, fld.name });
        }
    }
    try writer.writeAll("\n        )\n");

    // serialize method
    try writer.print(
        \\
        \\    def serialize(self, target: Target = Target.CPU) -> bytes:
        \\        """Serialize to bytes."""
        \\        s = self._to_struct()
        \\        out_len = c_size_t()
        \\        ptr = _lib.{s}_serialize(byref(s), int(target), byref(out_len))
        \\        if not ptr:
        \\            raise ZdlException(_get_last_error())
        \\        try:
        \\            return bytes(ptr[:out_len.value])
        \\        finally:
        \\            _lib.{s}_free(ptr)
        \\
    , .{ prefix, prefix });

    // deserialize method
    try writer.print(
        \\
        \\    @classmethod
        \\    def deserialize(cls, data: bytes) -> "{s}":
        \\        """Deserialize from bytes."""
        \\        buf = (c_uint8 * len(data)).from_buffer_copy(data)
        \\        ptr = _lib.{s}_deserialize(buf, len(data))
        \\        if not ptr:
        \\            raise ZdlException(_get_last_error())
        \\        try:
        \\            return cls._from_struct(ptr.contents)
        \\        finally:
        \\            _lib.{s}_free(ptr)
        \\
    , .{ type_name, prefix, prefix });

    // serialize_array method
    try writer.print(
        \\
        \\    @classmethod
        \\    def serialize_array(cls, items: List["{s}"], target: Target = Target.CPU) -> bytes:
        \\        """Serialize a list of items to bytes."""
        \\        arr_type = _{s}Struct * len(items)
        \\        arr = arr_type()
        \\        for i, item in enumerate(items):
        \\            arr[i] = item._to_struct()
        \\        out_len = c_size_t()
        \\        ptr = _lib.{s}_serialize_array(arr, len(items), int(target), byref(out_len))
        \\        if not ptr:
        \\            raise ZdlException(_get_last_error())
        \\        try:
        \\            return bytes(ptr[:out_len.value])
        \\        finally:
        \\            _lib.{s}_free(ptr)
        \\
    , .{ type_name, type_name, prefix, prefix });

    // array_count method
    try writer.print(
        \\
        \\    @classmethod
        \\    def array_count(cls, data: bytes) -> int:
        \\        """Get the count of items in serialized array data."""
        \\        buf = (c_uint8 * len(data)).from_buffer_copy(data)
        \\        return _lib.{s}_array_count(buf, len(data))
        \\
    , .{prefix});

    // field_count method
    try writer.print(
        \\
        \\    @classmethod
        \\    def field_count(cls) -> int:
        \\        """Get the number of fields in the struct."""
        \\        return _lib.{s}_field_count()
        \\
    , .{prefix});

    // struct_size method
    try writer.print(
        \\
        \\    @classmethod
        \\    def struct_size(cls) -> int:
        \\        """Get the size of the struct in bytes."""
        \\        return _lib.{s}_struct_size()
        \\
        \\
    , .{prefix});

    // Generate the Query class
    try writer.print(
        \\
        \\class {s}Query:
        \\    """
        \\    Query builder for {s} records.
        \\
        \\    Usage:
        \\        query = {s}Query(serialized_data)
        \\        results = query.filter("id", ">=", 10).limit(100).collect()
        \\    """
        \\
        \\    def __init__(self, data: bytes):
        \\        """Create a query from serialized array data."""
        \\        self._data = data  # Keep reference to prevent GC
        \\        self._buf = (c_uint8 * len(data)).from_buffer_copy(data)
        \\        self._handle = _lib.{s}_query_new(self._buf, len(data))
        \\        if not self._handle:
        \\            raise ZdlException(_get_last_error())
        \\
    , .{ type_name, type_name, type_name, prefix });

    try writer.print(
        \\
        \\    def __del__(self):
        \\        """Free the query handle."""
        \\        if hasattr(self, "_handle") and self._handle:
        \\            _lib.{s}_query_free(self._handle)
        \\            self._handle = None
        \\
    , .{prefix});

    try writer.print(
        \\
        \\    def __enter__(self) -> "{s}Query":
        \\        return self
        \\
        \\    def __exit__(self, *args) -> None:
        \\        if self._handle:
        \\            _lib.{s}_query_free(self._handle)
        \\            self._handle = None
        \\
    , .{ type_name, prefix });

    // filter method
    try writer.print(
        \\
        \\    def filter(self, field: str, op: Union[str, Comparison], value: Any) -> "{s}Query":
        \\        """
        \\        Add a filter condition.
        \\
        \\        Args:
        \\            field: Field name to filter on
        \\            op: Comparison operator ("==", "!=", "<", "<=", ">", ">=")
        \\            value: Value to compare against
        \\
        \\        Returns:
        \\            self for method chaining
        \\        """
        \\        if isinstance(op, str):
        \\            cmp = _cmp_from_str(op)
        \\        else:
        \\            cmp = op
        \\
        \\        field_bytes = field.encode("utf-8")
        \\
        \\        # Determine the appropriate filter function based on value type
        \\        if isinstance(value, bool):
        \\            code = _lib.{s}_query_filter_bool(self._handle, field_bytes, int(cmp), value)
        \\        elif isinstance(value, int):
        \\            if value >= 0:
        \\                code = _lib.{s}_query_filter_u64(self._handle, field_bytes, int(cmp), value)
        \\            else:
        \\                code = _lib.{s}_query_filter_i64(self._handle, field_bytes, int(cmp), value)
        \\        elif isinstance(value, float):
        \\            code = _lib.{s}_query_filter_f64(self._handle, field_bytes, int(cmp), value)
        \\        else:
        \\            raise TypeError(f"Unsupported filter value type: {{type(value)}}")
        \\
        \\        _check_error(code)
        \\        return self
        \\
    , .{ type_name, prefix, prefix, prefix, prefix });

    // limit method
    try writer.print(
        \\
        \\    def limit(self, n: int) -> "{s}Query":
        \\        """Set the maximum number of results to return."""
        \\        _check_error(_lib.{s}_query_limit(self._handle, n))
        \\        return self
        \\
    , .{ type_name, prefix });

    // offset method
    try writer.print(
        \\
        \\    def offset(self, n: int) -> "{s}Query":
        \\        """Set the number of results to skip."""
        \\        _check_error(_lib.{s}_query_offset(self._handle, n))
        \\        return self
        \\
    , .{ type_name, prefix });

    // collect method
    try writer.print(
        \\
        \\    def collect(self) -> List[{s}]:
        \\        """
        \\        Collect all matching results.
        \\
        \\        Note: You must call limit() before collect().
        \\        """
        \\        out_count = c_size_t()
        \\        ptr = _lib.{s}_query_collect(self._handle, byref(out_count))
        \\        if not ptr and out_count.value == 0:
        \\            return []
        \\        if not ptr:
        \\            raise ZdlException(_get_last_error())
        \\        try:
        \\            results = []
        \\            for i in range(out_count.value):
        \\                results.append({s}._from_struct(ptr[i]))
        \\            return results
        \\        finally:
        \\            _lib.{s}_free(ptr)
        \\
    , .{ type_name, prefix, type_name, prefix });

    // count method
    try writer.print(
        \\
        \\    def count(self) -> int:
        \\        """Count matching results without materializing them."""
        \\        return _lib.{s}_query_count(self._handle)
        \\
    , .{prefix});

    // __iter__ method
    try writer.print(
        \\
        \\    def __iter__(self) -> Iterator[{s}]:
        \\        """
        \\        Iterate over matching results.
        \\
        \\        Note: Each item is only valid until the next iteration.
        \\        """
        \\        code = _lib.{s}_query_iter_start(self._handle)
        \\        _check_error(code)
        \\
        \\        while True:
        \\            ptr = _lib.{s}_query_iter_next(self._handle)
        \\            if not ptr:
        \\                break
        \\            yield {s}._from_struct(ptr.contents)
        \\
    , .{ type_name, prefix, prefix, type_name });

    // reset method
    try writer.print(
        \\
        \\    def reset(self) -> None:
        \\        """Reset the iterator to the beginning."""
        \\        _lib.{s}_query_iter_reset(self._handle)
        \\
        \\
    , .{prefix});
}

fn ctypeForZigType(comptime T: type) []const u8 {
    return switch (@typeInfo(T)) {
        .bool => "c_bool",
        .int => |info| switch (info.bits) {
            8 => if (info.signedness == .unsigned) "c_uint8" else "c_int8",
            16 => if (info.signedness == .unsigned) "c_uint16" else "c_int16",
            32 => if (info.signedness == .unsigned) "c_uint32" else "c_int32",
            64 => if (info.signedness == .unsigned) "c_uint64" else "c_int64",
            else => "c_void_p",
        },
        .float => |info| switch (info.bits) {
            32 => "c_float",
            64 => "c_double",
            else => "c_void_p",
        },
        .array => |info| blk: {
            const child = ctypeForZigType(info.child);
            break :blk std.fmt.comptimePrint("{s} * {d}", .{ child, info.len });
        },
        else => "c_void_p",
    };
}

fn pytypeForZigType(comptime T: type) []const u8 {
    return switch (@typeInfo(T)) {
        .bool => "bool",
        .int => "int",
        .float => "float",
        .array => "bytes",
        else => "Any",
    };
}

fn defaultForZigType(comptime T: type) []const u8 {
    return switch (@typeInfo(T)) {
        .bool => "False",
        .int => "0",
        .float => "0.0",
        .array => |info| std.fmt.comptimePrint("b\"\\x00\" * {d}", .{info.len}),
        else => "None",
    };
}

fn isArrayType(comptime T: type) bool {
    return @typeInfo(T) == .array;
}
