const std = @import("std");
const zdl = @import("zdl");
const schemas = zdl.interop.schemas;
const c_header = zdl.codegen.c_header;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len < 2) {
        std.debug.print("usage: gen_js <output_dir>\n", .{});
        return error.InvalidArgs;
    }

    const output_dir_path = args[1];
    var dir = try std.fs.cwd().makeOpenPath(output_dir_path, .{});
    defer dir.close();

    {
        var file = try dir.createFile("zdl.mjs", .{ .truncate = true });
        defer file.close();

        var list = std.ArrayListUnmanaged(u8){};
        defer list.deinit(allocator);

        try generateJsModule(list.writer(allocator));
        try file.writeAll(list.items);

        std.debug.print("generated zdl.mjs\n", .{});
    }

    {
        // .d.mts (not .d.ts): TypeScript only associates declarations with an
        // .mjs import when the declaration file uses the .d.mts suffix.
        var file = try dir.createFile("zdl.d.mts", .{ .truncate = true });
        defer file.close();

        var list = std.ArrayListUnmanaged(u8){};
        defer list.deinit(allocator);

        try generateDtsModule(list.writer(allocator));
        try file.writeAll(list.items);

        std.debug.print("generated zdl.d.mts\n", .{});
    }
}

fn generateJsModule(writer: anytype) !void {
    try writer.writeAll(
        \\// zdl - Zero Data Layer JavaScript bindings (wasm64-freestanding)
        \\// Auto-generated by zdl - do not edit manually.
        \\//
        \\// Usage:
        \\//   import { loadZdl } from "./zdl.mjs";
        \\//   const zdl = await loadZdl(wasmBytes /* or WebAssembly.Module */);
        \\//   const { FfiUser, FfiUserQuery, FfiUserMutable } = zdl;
        \\//
        \\// Requires a runtime with WebAssembly Memory64 (Node >= 24, V8 13+,
        \\// recent Chrome/Firefox). Pointers and sizes cross the boundary as
        \\// BigInt; struct fields wider than 32 bits decode as BigInt.
        \\
        \\export const Target = Object.freeze({ CPU: 0, DISK: 1, NETWORK: 2 });
        \\
        \\export const Comparison = Object.freeze({ EQ: 0, NE: 1, LT: 2, LE: 3, GT: 4, GE: 5 });
        \\
        \\export const ZdlError = Object.freeze({
        \\  OK: 0, NULL_PARAM: 1, INVALID_FIELD: 2, TYPE_MISMATCH: 3,
        \\  BUFFER_CORRUPT: 4, OUT_OF_MEMORY: 5, LIMIT_EXCEEDED: 6,
        \\  LIMIT_REQUIRED: 7, TOO_MANY_FILTERS: 8, ITERATOR_NOT_STARTED: 9,
        \\  UNSUPPORTED_TYPE: 10, CAPACITY_FULL: 11, STALE_VIEW: 12,
        \\  SLOT_OUT_OF_RANGE: 13, SLOT_DELETED: 14, CHECKSUM_MISMATCH: 15,
        \\  VERSION_MISMATCH: 16, BUFFER_TOO_SMALL: 17, DATA_TOO_LARGE: 18,
        \\});
        \\
        \\const _ERR_NAMES = Object.fromEntries(
        \\  Object.entries(ZdlError).map(([k, v]) => [v, k]),
        \\);
        \\
        \\export class ZdlException extends Error {
        \\  constructor(code, message) {
        \\    super(`${_ERR_NAMES[code] ?? code}: ${message}`);
        \\    this.code = code;
        \\  }
        \\}
        \\
        \\const _CMP = {
        \\  "==": 0, "=": 0, eq: 0,
        \\  "!=": 1, "<>": 1, ne: 1,
        \\  "<": 2, lt: 2,
        \\  "<=": 3, le: 3,
        \\  ">": 4, gt: 4,
        \\  ">=": 5, ge: 5,
        \\};
        \\
        \\function _cmpOf(op) {
        \\  if (typeof op === "number") return op;
        \\  const cmp = _CMP[op];
        \\  if (cmp === undefined) throw new Error(`Unknown comparison operator: ${op}`);
        \\  return cmp;
        \\}
        \\
        \\/// Instantiate the zdl wasm module and return the bound API.
        \\/// `source` may be wasm bytes (BufferSource), a WebAssembly.Module, or
        \\/// a Response/Promise<Response> for streaming compilation in browsers.
        \\export async function loadZdl(source) {
        \\  let module;
        \\  if (source instanceof WebAssembly.Module) {
        \\    module = source;
        \\  } else if (typeof Response !== "undefined" &&
        \\             (source instanceof Response || source instanceof Promise)) {
        \\    module = await WebAssembly.compileStreaming(source);
        \\  } else {
        \\    module = await WebAssembly.compile(source);
        \\  }
        \\  const instance = await WebAssembly.instantiate(module, {});
        \\  const E = instance.exports;
        \\
        \\  // wasm64: pointers and sizes are BigInt. Views are created fresh at
        \\  // every use; memory growth detaches previous ArrayBuffers.
        \\  const P = (v) => (typeof v === "bigint" ? Number(v) : v);
        \\  const U = (v) => BigInt(v);
        \\
        \\  function _cstr(ptr) {
        \\    const b = new Uint8Array(E.memory.buffer);
        \\    let p = P(ptr), end = p;
        \\    while (b[end] !== 0) end++;
        \\    return new TextDecoder().decode(b.subarray(p, end));
        \\  }
        \\  function _errMessage(code) {
        \\    return _cstr(E.zdl_error_message(code));
        \\  }
        \\  function _check(code) {
        \\    if (code !== 0) throw new ZdlException(code, _errMessage(code));
        \\  }
        \\  function _throwLast() {
        \\    const code = E.zdl_last_error();
        \\    throw new ZdlException(code, _errMessage(code));
        \\  }
        \\  function _alloc(n) {
        \\    const ptr = E.zdl_alloc(U(n));
        \\    if (ptr === 0n) throw new ZdlException(ZdlError.OUT_OF_MEMORY, "Out of memory");
        \\    return ptr;
        \\  }
        \\  function _copyIn(data) {
        \\    if (typeof data === "string") data = new TextEncoder().encode(data);
        \\    const ptr = _alloc(data.length);
        \\    new Uint8Array(E.memory.buffer, P(ptr), data.length).set(data);
        \\    return ptr;
        \\  }
        \\  function _cstrIn(s) {
        \\    const enc = new TextEncoder().encode(s);
        \\    const ptr = _alloc(enc.length + 1);
        \\    const dst = new Uint8Array(E.memory.buffer, P(ptr), enc.length + 1);
        \\    dst.set(enc);
        \\    dst[enc.length] = 0;
        \\    return ptr;
        \\  }
        \\  function _copyOut(ptr, len) {
        \\    return new Uint8Array(E.memory.buffer, P(ptr), P(len)).slice();
        \\  }
        \\  function _readUsize(ptr) {
        \\    return new DataView(E.memory.buffer).getBigUint64(P(ptr), true);
        \\  }
        \\  function _setBytes(base, len, value) {
        \\    const dst = new Uint8Array(E.memory.buffer, base, len);
        \\    dst.fill(0);
        \\    if (value == null) return;
        \\    if (typeof value === "string") value = new TextEncoder().encode(value);
        \\    if (value.length > len) value = value.subarray ? value.subarray(0, len) : value.slice(0, len);
        \\    dst.set(value);
        \\  }
        \\  function _getBytes(base, len) {
        \\    return new Uint8Array(E.memory.buffer, base, len).slice();
        \\  }
        \\  function _toBig(v, field) {
        \\    try {
        \\      return BigInt(v);
        \\    } catch {
        \\      throw new TypeError(`Field "${field}": expected an integer (number or BigInt), got ${v}`);
        \\    }
        \\  }
        \\
    );

    inline for (schemas.registry) |entry| {
        try generateSchemaJs(entry.Type, entry.c_prefix, writer);
    }

    // Footer: return the bound API
    try writer.writeAll("  return {\n    instance,\n    Target,\n    Comparison,\n    ZdlError,\n");
    inline for (schemas.registry) |entry| {
        const type_name = c_header.simplifyTypeName(@typeName(entry.Type));
        try writer.print("    {s},\n    {s}Query,\n    {s}Mutable,\n", .{ type_name, type_name, type_name });
    }
    try writer.writeAll("  };\n}\n");
}

// Collect every struct type in T's field tree, children before parents,
// deduplicated — codecs are emitted once per type.
fn collectStructs(comptime T: type, comptime acc: []const type) []const type {
    comptime {
        for (acc) |S| {
            if (S == T) return acc;
        }
        var result = acc;
        for (std.meta.fields(T)) |field| {
            if (field.is_comptime) continue;
            result = collectFieldStructs(field.type, result);
        }
        return result ++ &[_]type{T};
    }
}

fn collectFieldStructs(comptime F: type, comptime acc: []const type) []const type {
    comptime {
        return switch (@typeInfo(F)) {
            .@"struct" => collectStructs(F, acc),
            .array => |info| collectFieldStructs(info.child, acc),
            else => acc,
        };
    }
}

fn generateSchemaJs(comptime T: type, comptime prefix: []const u8, writer: anytype) !void {
    const type_name = c_header.simplifyTypeName(@typeName(T));

    try writer.print("\n  // ========== {s} ==========\n\n", .{type_name});

    // Codecs for T and every nested struct, children first
    const struct_types = comptime collectStructs(T, &[_]type{});
    inline for (struct_types) |S| {
        try emitStructCodec(S, prefix, writer);
    }

    // Schema namespace: plain objects in, plain objects out
    try writer.print(
        \\  const {s} = {{
        \\    structSize: () => P(E.{s}_struct_size()),
        \\    fieldCount: () => P(E.{s}_field_count()),
        \\    serializedSize: (target = Target.CPU) => P(E.{s}_serialized_size(target)),
        \\
        \\    serialize(obj, target = Target.CPU) {{
        \\      const tmp = _alloc({d});
        \\      const outLen = _alloc(8);
        \\      try {{
        \\        _encode_{s}_{s}(P(tmp), obj);
        \\        const ptr = E.{s}_serialize(tmp, target, outLen);
        \\        if (ptr === 0n) _throwLast();
        \\        try {{
        \\          return _copyOut(ptr, _readUsize(outLen));
        \\        }} finally {{
        \\          E.{s}_free(ptr);
        \\        }}
        \\      }} finally {{
        \\        E.zdl_free(outLen);
        \\        E.zdl_free(tmp);
        \\      }}
        \\    }},
        \\
        \\    deserialize(data) {{
        \\      const buf = _copyIn(data);
        \\      try {{
        \\        const ptr = E.{s}_deserialize(buf, U(data.length));
        \\        if (ptr === 0n) _throwLast();
        \\        try {{
        \\          return _decode_{s}_{s}(P(ptr));
        \\        }} finally {{
        \\          E.{s}_free(ptr);
        \\        }}
        \\      }} finally {{
        \\        E.zdl_free(buf);
        \\      }}
        \\    }},
        \\
        \\    serializeArray(items, target = Target.CPU) {{
        \\      const tmp = _alloc(Math.max(1, items.length * {d}));
        \\      const outLen = _alloc(8);
        \\      try {{
        \\        for (let i = 0; i < items.length; i++) {{
        \\          _encode_{s}_{s}(P(tmp) + i * {d}, items[i]);
        \\        }}
        \\        const ptr = E.{s}_serialize_array(tmp, U(items.length), target, outLen);
        \\        if (ptr === 0n) _throwLast();
        \\        try {{
        \\          return _copyOut(ptr, _readUsize(outLen));
        \\        }} finally {{
        \\          E.{s}_free(ptr);
        \\        }}
        \\      }} finally {{
        \\        E.zdl_free(outLen);
        \\        E.zdl_free(tmp);
        \\      }}
        \\    }},
        \\
        \\    arrayCount(data) {{
        \\      const buf = _copyIn(data);
        \\      try {{
        \\        return P(E.{s}_array_count(buf, U(data.length)));
        \\      }} finally {{
        \\        E.zdl_free(buf);
        \\      }}
        \\    }},
        \\  }};
        \\
        \\
    , .{
        type_name, prefix,    prefix,    prefix,
        @sizeOf(T), prefix,   type_name, prefix,
        prefix,    prefix,    prefix,    type_name,
        prefix,    @sizeOf(T), prefix,   type_name,
        @sizeOf(T), prefix,   prefix,    prefix,
    });

    // Query class
    try writer.print(
        \\  class {s}Query {{
        \\    constructor(data) {{
        \\      this._buf = _copyIn(data);
        \\      this._len = U(data.length);
        \\      this._handle = E.{s}_query_new(this._buf, this._len);
        \\      if (this._handle === 0n) {{
        \\        E.zdl_free(this._buf);
        \\        _throwLast();
        \\      }}
        \\    }}
        \\
        \\    free() {{
        \\      if (this._handle) {{
        \\        E.{s}_query_free(this._handle);
        \\        this._handle = 0n;
        \\        E.zdl_free(this._buf);
        \\        this._buf = 0n;
        \\      }}
        \\    }}
        \\
        \\    filter(field, op, value) {{
        \\      const cmp = _cmpOf(op);
        \\      const fieldPtr = _cstrIn(field);
        \\      let code;
        \\      try {{
        \\        if (typeof value === "boolean") {{
        \\          code = E.{s}_query_filter_bool(this._handle, fieldPtr, cmp, value ? 1 : 0);
        \\        }} else if (typeof value === "bigint") {{
        \\          code = value < 0n
        \\            ? E.{s}_query_filter_i64(this._handle, fieldPtr, cmp, value)
        \\            : E.{s}_query_filter_u64(this._handle, fieldPtr, cmp, value);
        \\        }} else if (Number.isInteger(value)) {{
        \\          code = value < 0
        \\            ? E.{s}_query_filter_i64(this._handle, fieldPtr, cmp, BigInt(value))
        \\            : E.{s}_query_filter_u64(this._handle, fieldPtr, cmp, BigInt(value));
        \\        }} else if (typeof value === "number") {{
        \\          code = E.{s}_query_filter_f64(this._handle, fieldPtr, cmp, value);
        \\        }} else {{
        \\          throw new TypeError(`Unsupported filter value: ${{value}}`);
        \\        }}
        \\      }} finally {{
        \\        E.zdl_free(fieldPtr);
        \\      }}
        \\      _check(code);
        \\      return this;
        \\    }}
        \\
        \\    limit(n) {{
        \\      _check(E.{s}_query_limit(this._handle, U(n)));
        \\      return this;
        \\    }}
        \\
        \\    offset(n) {{
        \\      _check(E.{s}_query_offset(this._handle, U(n)));
        \\      return this;
        \\    }}
        \\
        \\    collect() {{
        \\      const outCount = _alloc(8);
        \\      try {{
        \\        const ptr = E.{s}_query_collect(this._handle, outCount);
        \\        const count = P(_readUsize(outCount));
        \\        if (ptr === 0n) {{
        \\          if (count === 0) return [];
        \\          _throwLast();
        \\        }}
        \\        try {{
        \\          const results = [];
        \\          for (let i = 0; i < count; i++) {{
        \\            results.push(_decode_{s}_{s}(P(ptr) + i * {d}));
        \\          }}
        \\          return results;
        \\        }} finally {{
        \\          E.{s}_free(ptr);
        \\        }}
        \\      }} finally {{
        \\        E.zdl_free(outCount);
        \\      }}
        \\    }}
        \\
        \\    count() {{
        \\      return P(E.{s}_query_count(this._handle));
        \\    }}
        \\
        \\    *[Symbol.iterator]() {{
        \\      _check(E.{s}_query_iter_start(this._handle));
        \\      for (;;) {{
        \\        const ptr = E.{s}_query_iter_next(this._handle);
        \\        if (ptr === 0n) {{
        \\          const code = E.zdl_last_error();
        \\          if (code !== 0) throw new ZdlException(code, _errMessage(code));
        \\          break;
        \\        }}
        \\        yield _decode_{s}_{s}(P(ptr));
        \\      }}
        \\    }}
        \\
        \\    reset() {{
        \\      E.{s}_query_iter_reset(this._handle);
        \\    }}
        \\  }}
        \\
        \\
    , .{
        type_name, prefix, prefix, prefix, prefix, prefix,
        prefix,    prefix, prefix, prefix, prefix, prefix,
        prefix,    type_name, @sizeOf(T), prefix, prefix,
        prefix,    prefix, prefix, type_name, prefix,
    });

    // Mutable container class — all reads return decoded copies, so pointer
    // lifetimes never leak into JS
    try writer.print(
        \\  class {s}Mutable {{
        \\    constructor(capacity = 16) {{
        \\      this._handle = E.{s}_mut_new(U(capacity));
        \\      if (this._handle === 0n) _throwLast();
        \\    }}
        \\
        \\    static load(data, extraCapacity = 0) {{
        \\      const buf = _copyIn(data);
        \\      let handle;
        \\      try {{
        \\        handle = E.{s}_mut_load(buf, U(data.length), U(extraCapacity));
        \\      }} finally {{
        \\        E.zdl_free(buf);
        \\      }}
        \\      if (handle === 0n) _throwLast();
        \\      const obj = Object.create({s}Mutable.prototype);
        \\      obj._handle = handle;
        \\      return obj;
        \\    }}
        \\
        \\    free() {{
        \\      if (this._handle) {{
        \\        E.{s}_mut_free(this._handle);
        \\        this._handle = 0n;
        \\      }}
        \\    }}
        \\
        \\    append(obj) {{
        \\      const tmp = _alloc({d});
        \\      const outSlot = _alloc(8);
        \\      try {{
        \\        _encode_{s}_{s}(P(tmp), obj);
        \\        _check(E.{s}_mut_append(this._handle, tmp, outSlot));
        \\        return P(_readUsize(outSlot));
        \\      }} finally {{
        \\        E.zdl_free(outSlot);
        \\        E.zdl_free(tmp);
        \\      }}
        \\    }}
        \\
        \\    get(slot) {{
        \\      const ptr = E.{s}_mut_get(this._handle, U(slot));
        \\      if (ptr === 0n) _throwLast();
        \\      return _decode_{s}_{s}(P(ptr));
        \\    }}
        \\
        \\    getVerified(slot) {{
        \\      const tmp = _alloc({d});
        \\      try {{
        \\        _check(E.{s}_mut_get_verified(this._handle, U(slot), tmp));
        \\        return _decode_{s}_{s}(P(tmp));
        \\      }} finally {{
        \\        E.zdl_free(tmp);
        \\      }}
        \\    }}
        \\
        \\    update(slot, obj) {{
        \\      const tmp = _alloc({d});
        \\      try {{
        \\        _encode_{s}_{s}(P(tmp), obj);
        \\        _check(E.{s}_mut_update(this._handle, U(slot), tmp));
        \\      }} finally {{
        \\        E.zdl_free(tmp);
        \\      }}
        \\    }}
        \\
        \\    delete(slot) {{
        \\      _check(E.{s}_mut_delete(this._handle, U(slot)));
        \\    }}
        \\
        \\    compact() {{
        \\      E.{s}_mut_compact(this._handle);
        \\    }}
        \\
        \\    reserve(additional) {{
        \\      _check(E.{s}_mut_reserve(this._handle, U(additional)));
        \\    }}
        \\
        \\    get live() {{
        \\      return P(E.{s}_mut_live(this._handle));
        \\    }}
        \\
        \\    get slots() {{
        \\      return P(E.{s}_mut_len(this._handle));
        \\    }}
        \\
        \\    get generation() {{
        \\      return E.{s}_mut_generation(this._handle);
        \\    }}
        \\
        \\    flush() {{
        \\      const outLen = _alloc(8);
        \\      try {{
        \\        const ptr = E.{s}_mut_flush(this._handle, outLen);
        \\        if (ptr === 0n) _throwLast();
        \\        try {{
        \\          return _copyOut(ptr, _readUsize(outLen));
        \\        }} finally {{
        \\          E.{s}_free(ptr);
        \\        }}
        \\      }} finally {{
        \\        E.zdl_free(outLen);
        \\      }}
        \\    }}
        \\
        \\    *[Symbol.iterator]() {{
        \\      _check(E.{s}_mut_iter_start(this._handle));
        \\      for (;;) {{
        \\        const ptr = E.{s}_mut_iter_next(this._handle);
        \\        if (ptr === 0n) {{
        \\          const code = E.zdl_last_error();
        \\          if (code !== 0) throw new ZdlException(code, _errMessage(code));
        \\          break;
        \\        }}
        \\        yield _decode_{s}_{s}(P(ptr));
        \\      }}
        \\    }}
        \\  }}
        \\
        \\
    , .{
        type_name, prefix,    prefix,    type_name, prefix,
        @sizeOf(T), prefix,   type_name, prefix,    prefix,
        prefix,    type_name, @sizeOf(T), prefix,   prefix,
        type_name, @sizeOf(T), prefix,   type_name, prefix,
        prefix,    prefix,    prefix,    prefix,    prefix,
        prefix,    prefix,    prefix,    prefix,    prefix,
        prefix,    type_name,
    });
}

fn emitStructCodec(comptime S: type, comptime prefix: []const u8, writer: anytype) !void {
    const name = c_header.simplifyTypeName(@typeName(S));
    const fields = std.meta.fields(S);

    // encode
    try writer.print("  function _encode_{s}_{s}(base, obj) {{\n", .{ prefix, name });
    try writer.writeAll("    obj = obj ?? {};\n    const v = new DataView(E.memory.buffer);\n");
    inline for (fields) |field| {
        if (field.is_comptime) continue;
        try emitEncodeField(field.type, field.name, @offsetOf(S, field.name), prefix, writer);
    }
    try writer.writeAll("  }\n\n");

    // decode
    try writer.print("  function _decode_{s}_{s}(base) {{\n", .{ prefix, name });
    try writer.writeAll("    const v = new DataView(E.memory.buffer);\n    return {\n");
    inline for (fields) |field| {
        if (field.is_comptime) continue;
        try emitDecodeField(field.type, field.name, @offsetOf(S, field.name), prefix, writer);
    }
    try writer.writeAll("    };\n  }\n\n");
}

fn emitEncodeField(
    comptime F: type,
    comptime field_name: []const u8,
    comptime offset: usize,
    comptime prefix: []const u8,
    writer: anytype,
) !void {
    switch (@typeInfo(F)) {
        .bool => try writer.print(
            "    v.setUint8(base + {d}, obj.{s} ? 1 : 0);\n",
            .{ offset, field_name },
        ),
        .int => |info| {
            const setter = comptime intSetter(info.bits, info.signedness);
            if (info.bits == 64) {
                try writer.print(
                    "    v.{s}(base + {d}, _toBig(obj.{s} ?? 0, \"{s}\"), true);\n",
                    .{ setter, offset, field_name, field_name },
                );
            } else {
                try writer.print(
                    "    v.{s}(base + {d}, obj.{s} ?? 0{s});\n",
                    .{ setter, offset, field_name, if (info.bits > 8) ", true" else "" },
                );
            }
        },
        .float => |info| try writer.print(
            "    v.set{s}(base + {d}, obj.{s} ?? 0, true);\n",
            .{ if (info.bits == 32) "Float32" else "Float64", offset, field_name },
        ),
        .array => |info| {
            if (info.child == u8) {
                try writer.print(
                    "    _setBytes(base + {d}, {d}, obj.{s});\n",
                    .{ offset, info.len, field_name },
                );
            } else switch (@typeInfo(info.child)) {
                .@"struct" => {
                    const child_name = c_header.simplifyTypeName(@typeName(info.child));
                    try writer.print(
                        "    for (let i = 0; i < {d}; i++) _encode_{s}_{s}(base + {d} + i * {d}, (obj.{s} ?? [])[i]);\n",
                        .{ info.len, prefix, child_name, offset, @sizeOf(info.child), field_name },
                    );
                },
                .int, .float, .bool => {
                    try writer.print(
                        "    for (let i = 0; i < {d}; i++) {{ const e = (obj.{s} ?? [])[i]; ",
                        .{ info.len, field_name },
                    );
                    try emitScalarElementSet(info.child, offset, @sizeOf(info.child), writer);
                    try writer.writeAll(" }\n");
                },
                else => @compileError("Unsupported array element type for JS bindings"),
            }
        },
        .@"struct" => {
            const child_name = c_header.simplifyTypeName(@typeName(F));
            try writer.print(
                "    _encode_{s}_{s}(base + {d}, obj.{s});\n",
                .{ prefix, child_name, offset, field_name },
            );
        },
        else => @compileError("Unsupported field type for JS bindings"),
    }
}

fn emitScalarElementSet(comptime C: type, comptime offset: usize, comptime stride: usize, writer: anytype) !void {
    switch (@typeInfo(C)) {
        .bool => try writer.print("v.setUint8(base + {d} + i * {d}, e ? 1 : 0);", .{ offset, stride }),
        .int => |info| {
            const setter = comptime intSetter(info.bits, info.signedness);
            if (info.bits == 64) {
                try writer.print("v.{s}(base + {d} + i * {d}, _toBig(e ?? 0, \"element\"), true);", .{ setter, offset, stride });
            } else {
                try writer.print("v.{s}(base + {d} + i * {d}, e ?? 0{s});", .{ setter, offset, stride, if (info.bits > 8) ", true" else "" });
            }
        },
        .float => |info| try writer.print(
            "v.set{s}(base + {d} + i * {d}, e ?? 0, true);",
            .{ if (info.bits == 32) "Float32" else "Float64", offset, stride },
        ),
        else => @compileError("Unsupported array element type for JS bindings"),
    }
}

fn emitDecodeField(
    comptime F: type,
    comptime field_name: []const u8,
    comptime offset: usize,
    comptime prefix: []const u8,
    writer: anytype,
) !void {
    switch (@typeInfo(F)) {
        .bool => try writer.print(
            "      {s}: v.getUint8(base + {d}) !== 0,\n",
            .{ field_name, offset },
        ),
        .int => |info| {
            const getter = comptime intGetter(info.bits, info.signedness);
            try writer.print(
                "      {s}: v.{s}(base + {d}{s}),\n",
                .{ field_name, getter, offset, if (info.bits > 8) ", true" else "" },
            );
        },
        .float => |info| try writer.print(
            "      {s}: v.get{s}(base + {d}, true),\n",
            .{ field_name, if (info.bits == 32) "Float32" else "Float64", offset },
        ),
        .array => |info| {
            if (info.child == u8) {
                try writer.print(
                    "      {s}: _getBytes(base + {d}, {d}),\n",
                    .{ field_name, offset, info.len },
                );
            } else switch (@typeInfo(info.child)) {
                .@"struct" => {
                    const child_name = c_header.simplifyTypeName(@typeName(info.child));
                    try writer.print(
                        "      {s}: Array.from({{ length: {d} }}, (_, i) => _decode_{s}_{s}(base + {d} + i * {d})),\n",
                        .{ field_name, info.len, prefix, child_name, offset, @sizeOf(info.child) },
                    );
                },
                .int, .float, .bool => {
                    try writer.print("      {s}: Array.from({{ length: {d} }}, (_, i) => ", .{ field_name, info.len });
                    try emitScalarElementGet(info.child, offset, @sizeOf(info.child), writer);
                    try writer.writeAll("),\n");
                },
                else => @compileError("Unsupported array element type for JS bindings"),
            }
        },
        .@"struct" => {
            const child_name = c_header.simplifyTypeName(@typeName(F));
            try writer.print(
                "      {s}: _decode_{s}_{s}(base + {d}),\n",
                .{ field_name, prefix, child_name, offset },
            );
        },
        else => @compileError("Unsupported field type for JS bindings"),
    }
}

fn emitScalarElementGet(comptime C: type, comptime offset: usize, comptime stride: usize, writer: anytype) !void {
    switch (@typeInfo(C)) {
        .bool => try writer.print("v.getUint8(base + {d} + i * {d}) !== 0", .{ offset, stride }),
        .int => |info| {
            const getter = comptime intGetter(info.bits, info.signedness);
            try writer.print("v.{s}(base + {d} + i * {d}{s})", .{ getter, offset, stride, if (info.bits > 8) ", true" else "" });
        },
        .float => |info| try writer.print(
            "v.get{s}(base + {d} + i * {d}, true)",
            .{ if (info.bits == 32) "Float32" else "Float64", offset, stride },
        ),
        else => @compileError("Unsupported array element type for JS bindings"),
    }
}

fn intSetter(comptime bits: u16, comptime signedness: std.builtin.Signedness) []const u8 {
    return switch (bits) {
        8 => if (signedness == .unsigned) "setUint8" else "setInt8",
        16 => if (signedness == .unsigned) "setUint16" else "setInt16",
        32 => if (signedness == .unsigned) "setUint32" else "setInt32",
        64 => if (signedness == .unsigned) "setBigUint64" else "setBigInt64",
        else => @compileError("Unsupported integer width for JS bindings"),
    };
}

fn intGetter(comptime bits: u16, comptime signedness: std.builtin.Signedness) []const u8 {
    return switch (bits) {
        8 => if (signedness == .unsigned) "getUint8" else "getInt8",
        16 => if (signedness == .unsigned) "getUint16" else "getInt16",
        32 => if (signedness == .unsigned) "getUint32" else "getInt32",
        64 => if (signedness == .unsigned) "getBigUint64" else "getBigInt64",
        else => @compileError("Unsupported integer width for JS bindings"),
    };
}

// ---------------------------------------------------------------------------
// TypeScript declarations (zdl.d.mts)
// ---------------------------------------------------------------------------

fn generateDtsModule(writer: anytype) !void {
    try writer.writeAll(
        \\// zdl - TypeScript declarations for zdl.mjs (wasm64-freestanding)
        \\// Auto-generated by zdl - do not edit manually.
        \\
        \\export declare const Target: Readonly<{ CPU: 0; DISK: 1; NETWORK: 2 }>;
        \\export type TargetValue = 0 | 1 | 2;
        \\
        \\export declare const Comparison: Readonly<{ EQ: 0; NE: 1; LT: 2; LE: 3; GT: 4; GE: 5 }>;
        \\export type CompareOp =
        \\  | 0 | 1 | 2 | 3 | 4 | 5
        \\  | "==" | "=" | "eq"
        \\  | "!=" | "<>" | "ne"
        \\  | "<" | "lt"
        \\  | "<=" | "le"
        \\  | ">" | "gt"
        \\  | ">=" | "ge";
        \\
        \\export declare const ZdlError: Readonly<{
        \\  OK: 0; NULL_PARAM: 1; INVALID_FIELD: 2; TYPE_MISMATCH: 3;
        \\  BUFFER_CORRUPT: 4; OUT_OF_MEMORY: 5; LIMIT_EXCEEDED: 6;
        \\  LIMIT_REQUIRED: 7; TOO_MANY_FILTERS: 8; ITERATOR_NOT_STARTED: 9;
        \\  UNSUPPORTED_TYPE: 10; CAPACITY_FULL: 11; STALE_VIEW: 12;
        \\  SLOT_OUT_OF_RANGE: 13; SLOT_DELETED: 14; CHECKSUM_MISMATCH: 15;
        \\  VERSION_MISMATCH: 16; BUFFER_TOO_SMALL: 17; DATA_TOO_LARGE: 18;
        \\}>;
        \\
        \\export declare class ZdlException extends Error {
        \\  readonly code: number;
        \\  constructor(code: number, message: string);
        \\}
        \\
        \\/** Bytes accepted wherever serialized data is consumed. */
        \\export type ByteSource = Uint8Array | ArrayLike<number>;
        \\
        \\
    );

    inline for (schemas.registry) |entry| {
        try generateSchemaDts(entry.Type, writer);
    }

    // The bound API returned by loadZdl
    try writer.writeAll("/** API bound to one instantiated zdl wasm module. */\nexport interface ZdlApi {\n");
    try writer.writeAll("  instance: WebAssembly.Instance;\n");
    try writer.writeAll("  Target: typeof Target;\n  Comparison: typeof Comparison;\n  ZdlError: typeof ZdlError;\n");
    inline for (schemas.registry) |entry| {
        const type_name = c_header.simplifyTypeName(@typeName(entry.Type));
        try writer.print("  {s}: {s}Static;\n  {s}Query: {s}QueryConstructor;\n  {s}Mutable: {s}MutableConstructor;\n", .{
            type_name, type_name, type_name, type_name, type_name, type_name,
        });
    }
    try writer.writeAll(
        \\}
        \\
        \\/** Instantiate the zdl wasm module (bytes, Module, or fetch Response)
        \\ *  and return the bound API. Requires WebAssembly Memory64. */
        \\export declare function loadZdl(
        \\  source: BufferSource | WebAssembly.Module | Response | Promise<Response>,
        \\): Promise<ZdlApi>;
        \\
    );
}

fn generateSchemaDts(comptime T: type, writer: anytype) !void {
    const type_name = c_header.simplifyTypeName(@typeName(T));

    // decoded + init interfaces for T and every nested struct
    const struct_types = comptime collectStructs(T, &[_]type{});
    inline for (struct_types) |S| {
        try emitStructInterfaces(S, writer);
    }

    // filterable fields: numeric (int/float) fields only, per the query module
    try writer.print("export type {s}FilterField =", .{type_name});
    comptime var any_filterable = false;
    inline for (std.meta.fields(T)) |field| {
        if (field.is_comptime) continue;
        switch (@typeInfo(field.type)) {
            .int, .float => {
                try writer.print("\n  | \"{s}\"", .{field.name});
                any_filterable = true;
            },
            else => {},
        }
    }
    if (!any_filterable) try writer.writeAll(" never");
    try writer.writeAll(";\n\n");

    try writer.print(
        \\export interface {s}Static {{
        \\  structSize(): number;
        \\  fieldCount(): number;
        \\  serializedSize(target?: TargetValue): number;
        \\  serialize(obj: {s}Init, target?: TargetValue): Uint8Array;
        \\  deserialize(data: ByteSource): {s};
        \\  serializeArray(items: readonly {s}Init[], target?: TargetValue): Uint8Array;
        \\  arrayCount(data: ByteSource): number;
        \\}}
        \\
        \\export interface {s}Query extends Iterable<{s}> {{
        \\  filter(field: {s}FilterField, op: CompareOp, value: number | bigint | boolean): this;
        \\  limit(n: number): this;
        \\  offset(n: number): this;
        \\  collect(): {s}[];
        \\  count(): number;
        \\  reset(): void;
        \\  free(): void;
        \\}}
        \\
        \\export interface {s}QueryConstructor {{
        \\  new (data: ByteSource): {s}Query;
        \\}}
        \\
        \\export interface {s}Mutable extends Iterable<{s}> {{
        \\  /** Append a record; returns its slot. Throws CAPACITY_FULL when out
        \\   *  of room (call reserve() first). */
        \\  append(obj: {s}Init): number;
        \\  /** Read the record at slot (decoded copy). */
        \\  get(slot: number): {s};
        \\  /** Integrity-checked read: verifies the record CRC (decoded copy). */
        \\  getVerified(slot: number): {s};
        \\  /** In-place update; re-CRCs exactly one record. */
        \\  update(slot: number, obj: {s}Init): void;
        \\  /** Tombstone delete: no bytes move; compact() reclaims. */
        \\  delete(slot: number): void;
        \\  /** Reclaim tombstones (relocation fence; order preserved). */
        \\  compact(): void;
        \\  /** Grow capacity (relocation fence; failure-atomic). */
        \\  reserve(additional: number): void;
        \\  /** Live (non-deleted) record count. */
        \\  readonly live: number;
        \\  /** Slots in use, including tombstoned ones. */
        \\  readonly slots: number;
        \\  /** Bumped whenever a fence (compact/reserve) relocates storage. */
        \\  readonly generation: bigint;
        \\  /** Serialize live records to an array container. */
        \\  flush(): Uint8Array;
        \\  free(): void;
        \\}}
        \\
        \\export interface {s}MutableConstructor {{
        \\  new (capacity?: number): {s}Mutable;
        \\  /** Load a serialized array container (validates container CRC). */
        \\  load(data: ByteSource, extraCapacity?: number): {s}Mutable;
        \\}}
        \\
        \\
    , .{
        type_name, type_name, type_name, type_name,
        type_name, type_name, type_name, type_name,
        type_name, type_name, type_name, type_name,
        type_name, type_name, type_name, type_name,
        type_name, type_name, type_name,
    });
}

fn emitStructInterfaces(comptime S: type, writer: anytype) !void {
    const name = c_header.simplifyTypeName(@typeName(S));

    // decoded shape (what reads return)
    try writer.print("export interface {s} {{\n", .{name});
    inline for (std.meta.fields(S)) |field| {
        if (field.is_comptime) continue;
        try writer.print("  {s}: {s};\n", .{ field.name, comptime tsDecodedType(field.type) });
    }
    try writer.writeAll("}\n\n");

    // init shape (what encodes accept; every field optional, zero-defaulted)
    try writer.print("export interface {s}Init {{\n", .{name});
    inline for (std.meta.fields(S)) |field| {
        if (field.is_comptime) continue;
        try writer.print("  {s}?: {s};\n", .{ field.name, comptime tsInitType(field.type) });
    }
    try writer.writeAll("}\n\n");
}

fn tsDecodedType(comptime F: type) []const u8 {
    return switch (@typeInfo(F)) {
        .bool => "boolean",
        .int => |info| if (info.bits == 64) "bigint" else "number",
        .float => "number",
        .array => |info| blk: {
            if (info.child == u8) break :blk "Uint8Array";
            break :blk switch (@typeInfo(info.child)) {
                .bool => "boolean[]",
                .int => |child| if (child.bits == 64) "bigint[]" else "number[]",
                .float => "number[]",
                .@"struct" => std.fmt.comptimePrint("{s}[]", .{c_header.simplifyTypeName(@typeName(info.child))}),
                else => @compileError("Unsupported array element type for TypeScript declarations"),
            };
        },
        .@"struct" => c_header.simplifyTypeName(@typeName(F)),
        else => @compileError("Unsupported field type for TypeScript declarations"),
    };
}

fn tsInitType(comptime F: type) []const u8 {
    return switch (@typeInfo(F)) {
        .bool => "boolean",
        .int => |info| if (info.bits == 64) "bigint | number" else "number",
        .float => "number",
        .array => |info| blk: {
            if (info.child == u8) break :blk "string | Uint8Array | ArrayLike<number>";
            break :blk switch (@typeInfo(info.child)) {
                .bool => "ArrayLike<boolean>",
                .int => |child| if (child.bits == 64) "ArrayLike<bigint | number>" else "ArrayLike<number>",
                .float => "ArrayLike<number>",
                .@"struct" => std.fmt.comptimePrint("readonly {s}Init[]", .{c_header.simplifyTypeName(@typeName(info.child))}),
                else => @compileError("Unsupported array element type for TypeScript declarations"),
            };
        },
        .@"struct" => std.fmt.comptimePrint("{s}Init", .{c_header.simplifyTypeName(@typeName(F))}),
        else => @compileError("Unsupported field type for TypeScript declarations"),
    };
}
